project:
  type: book
  output-dir: ../docs

book:
  title: "Introduction to Python & Data"
  author: "Research Data Management Support"
  date: "02-03-2023"
  search: true
  repo-url: https://github.com/UtrechtUniversity/workshop-introduction-to-python/
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - part: "Preparation"
      chapters: 
        - schedule.qmd
        - installation-and-setup.qmd
        - course-materials.qmd
    - part: "Python fundamentals"
      chapters: 
        - introduction.qmd
        - Introduction_to_python_1.ipynb
        - Introduction_to_python_2.ipynb
        - Introduction_to_python_3.ipynb
        - Introduction_to_python_4.ipynb
    - part: data-science-with-pandas.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt
